'use strict';

// This project is generated by AI self-evolution.

const axios = require('axios');
const http = require('http');
const cheerio = require('cheerio');  // 用于解析 HTML
const FormData = require('form-data');
const { google } = require('googleapis');

// ==================== 配置管理 ====================

/**
 * 多 LLM 提供商配置
 * 支持国内：阿里云百炼、智谱 AI、MiniMax、月之暗面
 * 支持国外：OpenAI、Anthropic、Google Gemini
 */
const LLM_PROVIDERS = {
    // ===== 国内 LLM =====
    bailian: {  // 阿里云百炼（默认）
        name: '阿里云百炼',
        baseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        models: ['qwen3.5-plus', 'qwen3-max-2026-01-23', 'qwen3-coder-plus', 'qwen3-coder-next'],
        defaultModel: 'qwen3.5-plus'
    },
    zhipu: {  // 智谱 AI
        name: '智谱 AI',
        baseURL: 'https://open.bigmodel.cn/api/paas/v4',
        models: ['glm-4', 'glm-4-air', 'glm-4-flash', 'glm-3-turbo'],
        defaultModel: 'glm-4'
    },
    minimax: {  // MiniMax
        name: 'MiniMax',
        baseURL: 'https://api.minimax.chat/v1',
        models: ['MiniMax-Text-01', 'MiniMax-VL-01'],
        defaultModel: 'MiniMax-Text-01'
    },
    moonshot: {  // 月之暗面（Kimi）
        name: 'Moonshot AI',
        baseURL: 'https://api.moonshot.cn/v1',
        models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
        defaultModel: 'moonshot-v1-32k'
    },
    deepseek: {  // 深度求索
        name: 'DeepSeek',
        baseURL: 'https://api.deepseek.com/v1',
        models: ['deepseek-chat', 'deepseek-reasoner'],
        defaultModel: 'deepseek-chat'
    },
    
    // ===== 国外 LLM =====
    openai: {  // OpenAI
        name: 'OpenAI',
        baseURL: 'https://api.openai.com/v1',
        models: ['gpt-4o', 'gpt-4-turbo', 'gpt-3.5-turbo'],
        defaultModel: 'gpt-4o'
    },
    anthropic: {  // Anthropic (Claude)
        name: 'Anthropic',
        baseURL: 'https://api.anthropic.com/v1',
        models: ['claude-3-opus-20240229', 'claude-3-sonnet-20240229', 'claude-3-haiku-20240307'],
        defaultModel: 'claude-3-sonnet-20240229',
        headers: {
            'x-api-key': '${ANTHROPIC_API_KEY}',
            'anthropic-version': '2023-06-01'
        }
    },
    google: {  // Google Gemini
        name: 'Google Gemini',
        baseURL: 'https://generativelanguage.googleapis.com/v1beta',
        models: ['gemini-1.5-pro', 'gemini-1.5-flash', 'gemini-1.0-pro'],
        defaultModel: 'gemini-1.5-pro'
    }
};

const CONFIG = {
    // LLM 配置（支持多提供商）
    LLM: {
        // 当前使用的提供商（bailian | zhipu | minimax | moonshot | deepseek | openai | anthropic | google）
        provider: process.env.LLM_PROVIDER || 'bailian',
        
        // API Key（根据提供商自动选择）
        apiKey: process.env.LLM_API_KEY,
        
        // 模型（可选，不填则使用提供商默认模型）
        model: process.env.LLM_MODEL,
        
        // 自定义 API 地址（可选，覆盖提供商默认地址）
        baseURL: process.env.LLM_BASE_URL
    },
    
    // 热点数据源
    HOTSPOT_SOURCES: {
        weibo: 'https://weibo.com/hot/list',
        douyin: 'https://www.douyin.com/hot',
        youtube: 'https://www.youtube.com/feed/trending',
        twitter: 'https://twitter.com/explore/tabs/trending'
    },
    
    // YouTube 配置
    YOUTUBE: {
        apiKey: process.env.YOUTUBE_API_KEY,
        channelId: process.env.YOUTUBE_CHANNEL_ID
    },
    
    // 视频生成配置
    VIDEO: {
        provider: process.env.VIDEO_PROVIDER || 'd-id',  // d-id / heygen / synthesia
        apiKey: process.env.VIDEO_API_KEY
    }
};

/** 每次读取环境变量，便于同一进程内测试脚本切换 MOCK / 提供商 */
function isMockMode() {
    return process.env.MOCK_MODE === 'true';
}

function currentLlmProvider(explicit) {
    return explicit || process.env.LLM_PROVIDER || 'bailian';
}

function hasLlmApiKey(providerName) {
    const p = providerName || currentLlmProvider();
    if (process.env.LLM_API_KEY) return true;
    return !!process.env[`${String(p).toUpperCase()}_API_KEY`];
}

// ==================== 主入口 ====================

exports.handler = async (event, context) => {
    try {
        const rawBody = typeof event.body === 'string' ? event.body : JSON.stringify(event.body || {});
        
        let body;
        try {
            body = rawBody ? JSON.parse(rawBody) : {};
        } catch (parseError) {
            log('ERROR', '请求 JSON 解析失败:', parseError.message);
            return response(400, { success: false, error: 'Invalid JSON body' });
        }

        const action = body.action;
        if (!action) {
            return response(400, { success: false, error: 'Missing action' });
        }
        
        log('INFO', `收到请求：${action}`);
        
        switch (action) {
            // 热点相关
            case 'get_hotspots':
                return await getHotspots(body);
            
            // 实时搜索热点
            case 'search_hotspots':
                return await searchHotspots(body);
            
            // 获取微博热搜
            case 'get_weibo_hot':
                return response(200, {
                    success: true,
                    data: await getWeiboHotRealtime(body)
                });
            
            // 获取知乎热榜
            case 'get_zhihu_hot':
                return response(200, {
                    success: true,
                    data: await getZhihuHotRealtime(body)
                });
            
            // 获取抖音热点
            case 'get_douyin_hot':
                return response(200, {
                    success: true,
                    data: await getDouyinHotRealtime(body)
                });
            
            // 获取百度热搜
            case 'get_baidu_hot':
                return response(200, {
                    success: true,
                    data: await getBaiduHotRealtime(body)
                });
            
            case 'analyze_hotspot':
                return await analyzeHotspot(body);
            
            // 脚本生成
            case 'generate_script':
                return await generateScript(body);
            
            // 视频生成
            case 'generate_video':
                return await generateVideo(body);
            
            // YouTube 上传
            case 'upload_to_youtube':
                return await uploadToYouTube(body);
            
            // 微信发布
            case 'publish_wechat':
                return await publishWeChat(body);
            
            // 微信一键生成
            case 'auto_create_wechat':
                return await autoCreateWeChatArticle(body);
            
            // 完整流程（一键式）
            case 'auto_create':
                return await autoCreateContent(body);
            
            // 频道管理
            case 'list_videos':
                return await listYouTubeVideos();
            
            case 'delete_video':
                return await deleteYouTubeVideo(body);
            
            // 健康检查
            case 'health':
                return response(200, { 
                    success: true, 
                    status: 'healthy',
                    timestamp: new Date().toISOString(),
                    mock: isMockMode()
                });
            
            default:
                return response(400, { success: false, error: 'Unknown action' });
        }
    } catch (error) {
        log('ERROR', '未处理异常:', error);
        return response(500, { 
            success: false, 
            error: error.message
        });
    }
};

// ==================== 热点获取模块 ====================

/**
 * 获取全网热点
 */
async function getHotspots(body) {
    const { platform = 'all', limit = 10 } = body;
    
    const hotspots = {
        weibo: [],
        douyin: [],
        youtube: [],
        twitter: [],
        zhihu: [],
        baidu: []
    };
    
    if (platform === 'all' || platform === 'weibo') {
        hotspots.weibo = await getWeiboHotRealtime({ limit });
    }
    
    if (platform === 'all' || platform === 'douyin') {
        hotspots.douyin = await getDouyinHotRealtime({ limit });
    }
    
    if (platform === 'all' || platform === 'zhihu') {
        hotspots.zhihu = await getZhihuHotRealtime({ limit });
    }
    
    if (platform === 'all' || platform === 'baidu') {
        hotspots.baidu = await getBaiduHotRealtime({ limit });
    }
    
    if (platform === 'all' || platform === 'youtube') {
        hotspots.youtube = await getYouTubeTrending(limit);
    }
    
    if (platform === 'all' || platform === 'twitter') {
        hotspots.twitter = await getTwitterTrending(limit);
    }
    
    return response(200, {
        success: true,
        data: hotspots,
        timestamp: new Date().toISOString()
    });
}

/**
 * 实时搜索热点（聚合搜索）
 */
async function searchHotspots(body) {
    const { keyword, platforms = ['weibo', 'zhihu', 'baidu'], limit = 10 } = body;
    
    if (!keyword) {
        throw new Error('缺少搜索关键词');
    }
    
    log('INFO', `实时搜索热点：${keyword}`);
    
    const results = {};
    
    // 并行搜索多个平台
    const searchTasks = platforms.map(async (platform) => {
        try {
            if (platform === 'weibo') {
                results.weibo = await searchWeibo(keyword, limit);
            } else if (platform === 'zhihu') {
                results.zhihu = await searchZhihu(keyword, limit);
            } else if (platform === 'baidu') {
                results.baidu = await searchBaidu(keyword, limit);
            }
        } catch (error) {
            log('ERROR', `${platform} 搜索失败:`, error.message);
            results[platform] = [];
        }
    });
    
    await Promise.all(searchTasks);
    
    return response(200, {
        success: true,
        data: results,
        keyword,
        timestamp: new Date().toISOString()
    });
}

/**
 * 获取微博热搜（实时）
 */
async function getWeiboHotRealtime(body) {
    const { limit = 10 } = body;
    
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟微博热搜数据');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'weibo',
            title: `微博热搜示例主题 ${i + 1}`,
            rank: i + 1,
            hot_value: 100000 - i * 1234,
            url: 'https://weibo.com'
        }));
    }
    
    try {
        // 使用第三方 API 或爬虫获取微博热搜
        // 这里使用示例数据，实际部署时替换为真实 API
        const response = await axios.get('https://weibo.com/ajax/side/hotSearch', {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
            },
            timeout: 5000
        });
        
        const data = response.data.data || [];
        return data.slice(0, limit).map(item => ({
            platform: 'weibo',
            title: item.word,
            rank: item.rank,
            hot_value: item.num,
            url: `https://s.weibo.com/weibo?q=${encodeURIComponent(item.word)}`,
            icon: item.icon,
            trend: item.flag_desc
        }));
    } catch (error) {
        log('ERROR', '获取微博热搜失败:', error.message);
        // 降级方案：返回缓存数据
        return [];
    }
}

/**
 * 获取知乎热榜（实时）
 */
async function getZhihuHotRealtime(body) {
    const { limit = 10 } = body;
    
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟知乎热榜数据');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'zhihu',
            title: `知乎热榜示例问题 ${i + 1}`,
            rank: i + 1,
            hot_value: 50000 - i * 800,
            url: 'https://www.zhihu.com/hot'
        }));
    }
    
    try {
        const response = await axios.get('https://www.zhihu.com/api/v3/feed/topstory/hot-list', {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
            },
            params: {
                limit: limit,
                reverse_order: 0
            },
            timeout: 5000
        });
        
        return (response.data.data || []).map(item => ({
            platform: 'zhihu',
            title: item.target.title,
            rank: item.id,
            hot_value: item.children[0].text,
            url: `https://www.zhihu.com/question/${item.target.id}`,
            excerpt: item.target.excerpt
        }));
    } catch (error) {
        log('ERROR', '获取知乎热榜失败:', error.message);
        return [];
    }
}

/**
 * 获取抖音热点（实时）
 */
async function getDouyinHotRealtime(body) {
    const { limit = 10 } = body;
    
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟抖音热点数据');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'douyin',
            title: `抖音热点示例话题 ${i + 1}`,
            rank: i + 1,
            hot_value: 80000 - i * 1000,
            url: 'https://www.douyin.com'
        }));
    }
    
    try {
        // 抖音热点 API（需要逆向或第三方服务）
        log('WARN', '抖音热点 API 需要特殊处理，返回示例数据');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'douyin',
            title: `抖音热点 ${i + 1}`,
            rank: i + 1,
            hot_value: 80000 - i * 1000,
            url: 'https://www.douyin.com/hot'
        }));
    } catch (error) {
        log('ERROR', '获取抖音热点失败:', error.message);
        return [];
    }
}

/**
 * 获取百度热搜（实时）
 */
async function getBaiduHotRealtime(body) {
    const { limit = 10 } = body;
    
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟百度热搜数据');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'baidu',
            title: `百度热搜示例 ${i + 1}`,
            rank: i + 1,
            hot_value: 90000 - i * 1100,
            url: 'https://top.baidu.com'
        }));
    }
    
    try {
        const response = await axios.get('https://top.baidu.com/board?tab=realtime', {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
            },
            timeout: 5000
        });
        
        // 解析 HTML（百度热搜是 HTML 页面）
        const $ = cheerio.load(response.data);
        const hotspots = [];
        
        $('.hot-item').each((i, el) => {
            if (i >= limit) return false;
            const title = $(el).find('.hot-title').text();
            const url = $(el).find('.hot-title').attr('href');
            const hot = $(el).find('.hot-score').text();
            const rank = i + 1;
            
            hotspots.push({
                platform: 'baidu',
                title,
                rank,
                hot_value: hot,
                url: url.startsWith('http') ? url : `https://top.baidu.com${url}`
            });
        });
        
        return hotspots;
    } catch (error) {
        log('ERROR', '获取百度热搜失败:', error.message);
        return [];
    }
}

/**
 * 搜索微博
 */
async function searchWeibo(keyword, limit = 10) {
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟微博搜索结果');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'weibo',
            title: `微博搜索示例 ${i + 1}（关键词：${keyword}）`,
            source: '微博搜索',
            url: 'https://weibo.com'
        }));
    }

    try {
        const response = await axios.get('https://s.weibo.com/weibo', {
            params: { q: keyword },
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
            },
            timeout: 5000
        });
        
        const $ = cheerio.load(response.data);
        const results = [];
        
        $('#pl_searchform_feed .card-wrap').each((i, el) => {
            if (i >= limit) return false;
            const title = $(el).find('.txt').text().trim();
            if (title) {
                results.push({
                    platform: 'weibo',
                    title,
                    source: '微博搜索'
                });
            }
        });
        
        return results;
    } catch (error) {
        log('ERROR', '搜索微博失败:', error.message);
        return [];
    }
}

/**
 * 搜索知乎
 */
async function searchZhihu(keyword, limit = 10) {
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟知乎搜索结果');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'zhihu',
            title: `知乎搜索示例 ${i + 1}（关键词：${keyword}）`,
            url: 'https://www.zhihu.com',
            source: '知乎搜索'
        }));
    }

    try {
        const response = await axios.get('https://www.zhihu.com/api/v3/search/search', {
            params: { q: keyword, type: 'content', limit },
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
            },
            timeout: 5000
        });
        
        return (response.data.data || []).map(item => ({
            platform: 'zhihu',
            title: item.object.title || item.object.content,
            url: `https://www.zhihu.com/question/${item.object.id}`,
            source: '知乎搜索'
        }));
    } catch (error) {
        log('ERROR', '搜索知乎失败:', error.message);
        return [];
    }
}

/**
 * 搜索百度
 */
async function searchBaidu(keyword, limit = 10) {
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟百度搜索结果');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'baidu',
            title: `百度搜索示例 ${i + 1}（关键词：${keyword}）`,
            url: 'https://www.baidu.com',
            source: '百度搜索'
        }));
    }

    try {
        const response = await axios.get('https://www.baidu.com/s', {
            params: { wd: keyword, rn: limit },
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
            },
            timeout: 5000
        });
        
        const $ = cheerio.load(response.data);
        const results = [];
        
        $('.result.c-container').each((i, el) => {
            if (i >= limit) return false;
            const title = $(el).find('.t').text().trim();
            const url = $(el).find('a').attr('href');
            
            if (title) {
                results.push({
                    platform: 'baidu',
                    title,
                    url,
                    source: '百度搜索'
                });
            }
        });
        
        return results;
    } catch (error) {
        log('ERROR', '搜索百度失败:', error.message);
        return [];
    }
}

/**
 * 获取 YouTube 趋势视频
 */
async function getYouTubeTrending(limit = 10) {
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟 YouTube 趋势数据');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'youtube',
            title: `YouTube Trending Sample Video ${i + 1}`,
            rank: 1000000 - i * 5432,
            video_id: `mock-video-${i + 1}`,
            url: `https://www.youtube.com/watch?v=mock-video-${i + 1}`
        }));
    }
    
    if (!process.env.YOUTUBE_API_KEY) {
        log('WARN', '未配置 YouTube API Key');
        return [];
    }
    
    try {
        const response = await axios.get('https://www.googleapis.com/youtube/v3/videos', {
            params: {
                part: 'snippet,statistics',
                chart: 'mostPopular',
                maxResults: limit,
                regionCode: 'US',
                key: process.env.YOUTUBE_API_KEY
            }
        });
        
        return response.data.items.map(item => ({
            platform: 'youtube',
            title: item.snippet.title,
            rank: item.statistics.viewCount,
            video_id: item.id,
            url: `https://www.youtube.com/watch?v=${item.id}`
        }));
    } catch (error) {
        log('ERROR', '获取 YouTube 趋势失败:', error.message);
        return [];
    }
}

/**
 * 获取 Twitter 趋势
 */
async function getTwitterTrending(limit = 10) {
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟 Twitter 趋势数据');
        return Array.from({ length: limit }).map((_, i) => ({
            platform: 'twitter',
            title: `Twitter Trending 示例 ${i + 1}`,
            rank: 100000 - i * 111,
            url: 'https://twitter.com'
        }));
    }

    const bearer = process.env.TWITTER_BEARER_TOKEN;
    if (!bearer) {
        log('INFO', '未配置 TWITTER_BEARER_TOKEN，Twitter 趋势返回空');
        return [];
    }

    const woeid = process.env.TWITTER_WOEID || '1';
    try {
        const resp = await axios.get('https://api.twitter.com/1.1/trends/place.json', {
            params: { id: woeid },
            headers: { Authorization: `Bearer ${bearer}` },
            timeout: 15000
        });
        const trends = (resp.data && resp.data[0] && resp.data[0].trends) || [];
        return trends.slice(0, limit).map((t, i) => ({
            platform: 'twitter',
            title: t.name,
            rank: typeof t.tweet_volume === 'number' ? t.tweet_volume : (1000000 - i * 1000),
            url: t.url || 'https://twitter.com'
        }));
    } catch (error) {
        log('ERROR', '获取 Twitter 趋势失败:', error.response?.data || error.message);
        return [];
    }
}

// ==================== AI 分析模块 ====================

/**
 * 分析热点话题
 */
async function analyzeHotspot(body) {
    const { topic, platform, hot_value } = body;
    
    if (!hasLlmApiKey() && !isMockMode()) {
        throw new Error('未配置 LLM API Key');
    }
    
    const analysisRaw = await callLLM(`
你是一个专业的内容分析师。请分析以下热点话题：

话题：${topic}
平台：${platform}
热度：${hot_value || '未知'}

请分析：
1. 这个话题为什么火？（核心原因）
2. 目标受众是谁？
3. 可以从哪些角度创作内容？（至少 3 个角度）
4. 有什么争议点或讨论价值？

输出格式：JSON（不要包含多余注释或说明）
{
    "reason": "火爆原因",
    "audience": "目标受众",
    "angles": ["角度 1", "角度 2", "角度 3"],
    "controversy": "争议点"
}
`);
    
    let parsed;
    try {
        parsed = JSON.parse(analysisRaw);
    } catch (e) {
        log('WARN', 'LLM 返回的分析结果不是严格 JSON，按文本返回');
        parsed = { raw: analysisRaw };
    }
    
    return response(200, {
        success: true,
        data: parsed
    });
}

// ==================== 脚本生成模块 ====================

/**
 * 生成口播稿核心逻辑（供内部复用）
 */
async function generateScriptCore({ topic, style = 'informative', duration = 60, provider } = {}) {
    if (!hasLlmApiKey(currentLlmProvider(provider)) && !isMockMode()) {
        throw new Error('未配置 LLM API Key');
    }
    
    // 计算字数（中文约 4 字/秒）
    const targetWords = duration * 4;
    
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟脚本内容');
        const mockScript = `【模拟脚本】主题：${topic}，风格：${style}，预期时长：${duration} 秒。`;
        return {
            script: mockScript,
            word_count: mockScript.length,
            estimated_duration: duration
        };
    }
    
    const script = await callLLM(`
你是一个专业的短视频口播稿写手。请根据以下主题生成一个口播稿。

主题：${topic}
风格：${style}（informative=知识科普，entertaining=娱乐搞笑，inspirational=励志鸡汤）
时长：${duration}秒（约${targetWords}字）

要求：
- 开头：用问题或金句吸引注意力（5 秒）
- 主体：3 个核心观点，每个观点配 1 个例子（${duration - 15}秒）
- 结尾：引导评论或关注（10 秒）
- 语气：自然、像和朋友聊天
- 避免：AI 味、说教感

请直接输出口播稿，不要其他说明。
`, { provider: currentLlmProvider(provider) });
    
    return {
        script,
        word_count: script.length,
        estimated_duration: Math.round(script.length / 4)
    };
}

/**
 * 生成口播稿（HTTP Handler）
 */
async function generateScript(body) {
    const { topic, style = 'informative', duration = 60, provider } = body;
    
    const data = await generateScriptCore({ topic, style, duration, provider });
    
    return response(200, {
        success: true,
        data
    });
}

// ==================== 视频生成模块 ====================

/**
 * 生成视频核心逻辑
 */
async function generateVideoCore({ script, video_type = 'talking_head' }) {
    if (!process.env.VIDEO_API_KEY && !isMockMode()) {
        throw new Error('未配置视频生成 API Key');
    }
    
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟视频生成结果');
        return {
            video_url: 'https://example.com/mock-video.mp4',
            talk_id: 'mock-talk-id'
        };
    }
    
    // 这里以 D-ID 为例（数字人视频）
    if (video_type === 'talking_head') {
        return await generateTalkingHeadVideo(script);
    }
    
    // 图文视频
    if (video_type === 'slideshow') {
        return await generateSlideshowVideo(script);
    }
    
    throw new Error('不支持的视频类型');
}

/**
 * 生成视频（HTTP Handler）
 */
async function generateVideo(body) {
    const { script, video_type = 'talking_head' } = body;
    
    const data = await generateVideoCore({ script, video_type });
    
    return response(200, {
        success: true,
        data
    });
}

/**
 * 生成数字人视频（D-ID）
 */
async function generateTalkingHeadVideo(script) {
    // D-ID API 文档：https://docs.d-id.com/
    
    // 1. 创建演讲
    let createResponse;
    try {
        createResponse = await axios.post(
            'https://api.d-id.com/talks',
            {
                script: {
                    type: 'text',
                    input: script,
                    provider: {
                        type: 'microsoft',
                        voice_id: 'zh-CN-XiaoxiaoNeural'
                    }
                },
                source_url: process.env.D_ID_SOURCE_URL || 'https://example.com/avatar.jpg'
            },
            {
                headers: {
                    'Authorization': `Basic ${process.env.VIDEO_API_KEY}`,
                    'Content-Type': 'application/json'
                }
            }
        );
    } catch (error) {
        log('ERROR', '调用 D-ID 创建视频失败:', error.message);
        throw new Error('视频生成服务调用失败，请稍后重试');
    }
    
    const talkId = createResponse.data.id;
    
    // 2. 等待视频生成（轮询）
    let status = 'created';
    let videoUrl = null;
    
    let attempts = 0;
    const maxAttempts = 40; // 最长约 2 分钟
    while ((status === 'created' || status === 'started') && attempts < maxAttempts) {
        attempts += 1;
        await sleep(3000);
        
        try {
            const statusResponse = await axios.get(
                `https://api.d-id.com/talks/${talkId}`,
                {
                    headers: {
                        'Authorization': `Basic ${process.env.VIDEO_API_KEY}`
                    }
                }
            );
            
            status = statusResponse.data.status;
            videoUrl = statusResponse.data.result_url;
        } catch (error) {
            log('ERROR', '轮询 D-ID 视频状态失败:', error.message);
            break;
        }
    }
    
    if (!videoUrl) {
        throw new Error('视频生成超时或失败');
    }
    
    return {
        video_url: videoUrl,
        talk_id: talkId
    };
}

/**
 * 生成图文视频
 */
async function generateSlideshowVideo(script) {
    const webhook = process.env.SLIDESHOW_WEBHOOK_URL;
    if (!webhook) {
        throw new Error('未配置 SLIDESHOW_WEBHOOK_URL：请提供自建服务，POST { script, type } 并返回 JSON { video_url }');
    }
    log('INFO', '调用图文视频 Webhook');
    const r = await axios.post(
        webhook,
        { script, type: 'slideshow' },
        { timeout: Number(process.env.SLIDESHOW_WEBHOOK_TIMEOUT_MS) || 120000, headers: { 'Content-Type': 'application/json' } }
    );
    const url = r.data && (r.data.video_url || r.data.url);
    if (!url) {
        throw new Error('图文视频 Webhook 未返回 video_url');
    }
    return {
        video_url: url,
        message: '图文视频生成成功'
    };
}

// ==================== 微信 / YouTube 真实链路辅助 ====================

async function fetchWeChatAccessToken() {
    const appId = process.env.WECHAT_APP_ID;
    const appSecret = process.env.WECHAT_APP_SECRET;
    if (!appId || !appSecret) {
        throw new Error('未配置微信公众号 APP_ID 或 APP_SECRET');
    }
    const tokenResponse = await axios.get('https://api.weixin.qq.com/cgi-bin/token', {
        params: {
            grant_type: 'client_credential',
            appid: appId,
            secret: appSecret
        },
        timeout: 10000
    });
    if (tokenResponse.data.errcode) {
        throw new Error(`获取 access_token 失败：${tokenResponse.data.errmsg || tokenResponse.data.errcode}`);
    }
    const accessToken = tokenResponse.data.access_token;
    if (!accessToken) {
        throw new Error('获取 access_token 失败：响应无 access_token');
    }
    return accessToken;
}

/**
 * 上传永久素材（thumb：封面图，≤64KB）
 */
async function uploadWeChatThumbMaterial(accessToken, imageBuffer, filename = 'cover.jpg') {
    const url = `https://api.weixin.qq.com/cgi-bin/material/add_material?access_token=${accessToken}&type=thumb`;
    const form = new FormData();
    form.append('media', imageBuffer, { filename });
    const res = await axios.post(url, form, {
        headers: form.getHeaders(),
        maxBodyLength: Infinity,
        maxContentLength: Infinity,
        timeout: 60000
    });
    if (res.data.errcode && res.data.errcode !== 0) {
        throw new Error(`上传封面素材失败：${res.data.errmsg || res.data.errcode}`);
    }
    if (!res.data.media_id) {
        throw new Error('上传封面素材失败：未返回 media_id');
    }
    return res.data.media_id;
}

async function resolveWeChatThumbMediaId(accessToken, cover_image) {
    const preset = process.env.WECHAT_DEFAULT_THUMB_MEDIA_ID;
    if (preset) {
        return preset;
    }
    if (!cover_image) {
        throw new Error('微信公众号图文需要 thumb_media_id：请传 cover_image（可访问的图片 URL），或配置 WECHAT_DEFAULT_THUMB_MEDIA_ID');
    }
    if (!/^https?:\/\//i.test(String(cover_image))) {
        throw new Error('cover_image 需为 http(s) 图片地址');
    }
    const imgRes = await axios.get(cover_image, { responseType: 'arraybuffer', timeout: 30000, maxContentLength: 70 * 1024 });
    const buf = Buffer.from(imgRes.data);
    if (buf.length > 64 * 1024) {
        throw new Error('封面图超过 64KB，请先压缩后再上传，或配置 WECHAT_DEFAULT_THUMB_MEDIA_ID');
    }
    return await uploadWeChatThumbMaterial(accessToken, buf, 'cover.jpg');
}

function getYouTubeOAuth2Client() {
    const clientId = process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
    const refreshToken = process.env.GOOGLE_REFRESH_TOKEN;
    if (!clientId || !clientSecret || !refreshToken) {
        throw new Error('YouTube 上传/删除需要 OAuth：请配置 GOOGLE_CLIENT_ID、GOOGLE_CLIENT_SECRET、GOOGLE_REFRESH_TOKEN');
    }
    const oauth2Client = new google.auth.OAuth2(
        clientId,
        clientSecret,
        process.env.GOOGLE_OAUTH_REDIRECT_URI || 'http://localhost'
    );
    oauth2Client.setCredentials({ refresh_token: refreshToken });
    return oauth2Client;
}

// ==================== 微信发布模块 ====================

/**
 * 发布到微信公众号
 */
async function publishWeChat(body) {
    const {
        title,
        content,
        cover_image,
        summary,
        author,
        content_source_url,
        need_open_comment,
        only_fans_can_comment
    } = body;
    
    if (!title || !content) {
        throw new Error('缺少必需参数：title 和 content');
    }
    
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，模拟发布微信公众号文章');
        return response(200, {
            success: true,
            data: {
                message: '文章发布成功（MOCK）',
                article_url: 'https://mp.weixin.qq.com/s/mock-article-id',
                media_id: 'mock-media-id'
            }
        });
    }
    
    const accessToken = await fetchWeChatAccessToken();
    const thumbMediaId = await resolveWeChatThumbMediaId(accessToken, cover_image);
    
    const draftPayload = {
        articles: [
            {
                title,
                author: author || process.env.WECHAT_ARTICLE_AUTHOR || 'AutoContent Factory',
                digest: (summary || title).slice(0, 120),
                content,
                content_source_url: content_source_url || '',
                thumb_media_id: thumbMediaId,
                need_open_comment: need_open_comment ? 1 : 0,
                only_fans_can_comment: only_fans_can_comment ? 1 : 0
            }
        ]
    };
    
    const publishResponse = await axios.post(
        `https://api.weixin.qq.com/cgi-bin/draft/add?access_token=${accessToken}`,
        draftPayload,
        { timeout: 60000 }
    );
    
    if (publishResponse.data.errcode && publishResponse.data.errcode !== 0) {
        throw new Error(`微信草稿失败：${publishResponse.data.errmsg || publishResponse.data.errcode}`);
    }
    
    return response(200, {
        success: true,
        data: {
            message: '文章已写入公众号草稿箱，请在微信公众平台后台审核并发布',
            media_id: publishResponse.data.media_id,
            item: publishResponse.data.item
        }
    });
}

// ==================== YouTube 上传模块 ====================

/**
 * 上传视频到 YouTube
 */
async function uploadToYouTube(body) {
    const { video_url, title, description, tags, privacy = 'private' } = body;
    
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，模拟上传 YouTube 视频');
        return response(200, {
            success: true,
            data: {
                message: '视频上传成功（MOCK）',
                video_id: 'mock-youtube-video-id'
            }
        });
    }
    
    if (!video_url) {
        throw new Error('缺少必需参数：video_url（可访问的视频文件 URL）');
    }
    
    const auth = getYouTubeOAuth2Client();
    const youtube = google.youtube({ version: 'v3', auth });
    
    const videoStream = await axios.get(video_url, {
        responseType: 'stream',
        timeout: 0,
        maxContentLength: Infinity,
        maxBodyLength: Infinity
    });
    
    const result = await youtube.videos.insert({
        part: ['snippet', 'status'],
        requestBody: {
            snippet: {
                title: title || 'Untitled',
                description: description || '',
                tags: Array.isArray(tags) ? tags : [],
                categoryId: body.category_id || '22'
            },
            status: {
                privacyStatus: privacy,
                selfDeclaredMadeForKids: false
            }
        },
        media: {
            body: videoStream.data
        }
    });
    
    const vid = result.data.id;
    return response(200, {
        success: true,
        data: {
            message: '视频上传成功',
            video_id: vid,
            url: `https://www.youtube.com/watch?v=${vid}`
        }
    });
}

/**
 * 列出 YouTube 频道视频
 */
async function listYouTubeVideos() {
    if (!process.env.YOUTUBE_API_KEY && !isMockMode()) {
        throw new Error('未配置 YouTube API Key');
    }
    
    if (isMockMode()) {
        log('INFO', 'MOCK_MODE 启用，返回模拟频道视频列表');
        return response(200, {
            success: true,
            data: [
                { id: { videoId: 'mock-video-1' }, snippet: { title: 'Mock Video 1' } },
                { id: { videoId: 'mock-video-2' }, snippet: { title: 'Mock Video 2' } }
            ]
        });
    }
    
    const res = await axios.get(
        'https://www.googleapis.com/youtube/v3/search',
        {
            params: {
                part: 'snippet',
                channelId: process.env.YOUTUBE_CHANNEL_ID,
                order: 'date',
                type: 'video',
                maxResults: 10,
                key: process.env.YOUTUBE_API_KEY
            }
        }
    );
    
    return response(200, {
        success: true,
        data: res.data.items
    });
}

/**
 * 删除 YouTube 视频
 */
async function deleteYouTubeVideo(body) {
    const { video_id } = body;
    
    if (isMockMode()) {
        log('INFO', `MOCK_MODE 启用，模拟删除视频 ${video_id}`);
        return response(200, {
            success: true,
            data: {
                message: `视频 ${video_id} 已删除（MOCK）`
            }
        });
    }
    
    if (!video_id) {
        throw new Error('缺少必需参数：video_id');
    }
    
    const auth = getYouTubeOAuth2Client();
    const youtube = google.youtube({ version: 'v3', auth });
    await youtube.videos.delete({ id: video_id });
    
    return response(200, {
        success: true,
        data: {
            message: `视频 ${video_id} 已删除`,
            video_id
        }
    });
}

// ==================== 一键自动化流程 ====================

/**
 * 自动创建微信公众号文章（完整流程）
 */
async function autoCreateWeChatArticle(body) {
    const { topic, platform = 'weibo', style = 'informative', provider, cover_image } = body;
    
    log('INFO', `开始自动创建微信文章：${topic}`);
    
    // 1. 生成脚本/文章内容
    log('INFO', '步骤 1/2: 生成文章内容...');
    const scriptResult = await generateScriptCore({
        topic,
        style,
        duration: 300,  // 5 分钟阅读时长
        provider
    });
    
    // 将脚本转换为微信文章格式（添加 HTML 标签）
    const articleContent = formatWeChatArticle(scriptResult.script, topic);
    log('INFO', `文章内容生成完成，${articleContent.length}字`);
    
    // 2. 发布到微信
    log('INFO', '步骤 2/2: 发布到微信公众号...');
    const publishResult = await publishWeChat({
        title: topic,
        content: articleContent,
        summary: `关于${topic}的深度解析`,
        cover_image: cover_image || process.env.WECHAT_DEFAULT_COVER_IMAGE_URL
    });
    
    return response(200, {
        success: true,
        data: {
            article: {
                topic,
                content: scriptResult.script,
                word_count: scriptResult.word_count
            },
            publish: JSON.parse(publishResult.body).data,
            status: 'completed'
        }
    });
}

/**
 * 将脚本格式化为微信文章 HTML
 */
function formatWeChatArticle(script, topic) {
    // 简单的 Markdown 转 HTML
    const html = script
        .split('\n')
        .map(line => {
            if (line.startsWith('# ')) {
                return `<h1>${line.slice(2)}</h1>`;
            } else if (line.startsWith('## ')) {
                return `<h2>${line.slice(3)}</h2>`;
            } else if (line.startsWith('### ')) {
                return `<h3>${line.slice(4)}</h3>`;
            } else if (line.trim()) {
                return `<p>${line}</p>`;
            }
            return '';
        })
        .join('\n');
    
    return `
<section>
    <h1 style="text-align: center; color: #333;">${topic}</h1>
    <p style="text-align: center; color: #999; font-size: 12px;">本文由 AI 自动生成</p>
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
    ${html}
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
    <p style="color: #999; font-size: 12px; text-align: center;">
        🤖 本文内容由 AutoContent Factory 自动生成
    </p>
</section>
    `.trim();
}

/**
 * 自动创建内容（完整流程）
 */
async function autoCreateContent(body) {
    const { topic, platform = 'youtube', style = 'informative', provider } = body;
    
    log('INFO', `开始自动创建内容：${topic}`);
    
    // 1. 生成脚本
    log('INFO', '步骤 1/3: 生成脚本...');
    const scriptResult = await generateScriptCore({
        topic,
        style,
        duration: 60,
        provider
    });
    
    const script = scriptResult.script;
    log('INFO', `脚本生成完成，${script.length}字`);
    
    // 2. 生成视频
    log('INFO', '步骤 2/3: 生成视频...');
    const videoResult = await generateVideoCore({
        script,
        video_type: 'talking_head'
    });
    
    log('INFO', `视频生成完成：${videoResult.video_url}`);
    
    // 3. 上传到 YouTube
    log('INFO', '步骤 3/3: 上传到 YouTube...');
    const uploadResult = await uploadToYouTube({
        video_url: videoResult.video_url,
        title: topic,
        description: `关于${topic}的分享\n\n#${topic.replace(/\s/g, '')} #AI 生成`,
        tags: [topic, 'AI', '自动化'],
        privacy: 'private'  // 先设为私密，审核后可改为 public
    });
    
    return response(200, {
        success: true,
        data: {
            script: scriptResult,
            video: videoResult,
            youtube: JSON.parse(uploadResult.body).data,
            status: 'completed'
        }
    });
}

// ==================== 工具函数 ====================

/**
 * 调用 LLM API（支持多提供商）
 */
async function callLLM(prompt, options = {}) {
    const providerName = currentLlmProvider(options.provider);
    const provider = LLM_PROVIDERS[providerName];
    
    if (!provider) {
        throw new Error(`不支持的 LLM 提供商：${providerName}。支持的提供商：${Object.keys(LLM_PROVIDERS).join(', ')}`);
    }
    
    const apiKey = process.env.LLM_API_KEY || process.env[`${providerName.toUpperCase()}_API_KEY`];
    
    if (!apiKey && !isMockMode()) {
        throw new Error(`未配置 ${provider.name} API Key。请设置 LLM_API_KEY 或 ${providerName.toUpperCase()}_API_KEY`);
    }
    
    if (isMockMode()) {
        log('INFO', `MOCK_MODE 启用，跳过 ${provider.name} 调用`);
        return `{"reason":"示例原因","audience":"示例受众","angles":["角度 1","角度 2","角度 3"],"controversy":"示例争议点"}`;
    }
    
    const model = options.model || process.env.LLM_MODEL || provider.defaultModel;
    const baseURL = process.env.LLM_BASE_URL || provider.baseURL;
    
    log('INFO', `调用 ${provider.name} (${model})`);
    
    // Anthropic 特殊处理
    if (providerName === 'anthropic') {
        return await callAnthropic(prompt, model, apiKey, baseURL);
    }
    
    // Google Gemini 特殊处理
    if (providerName === 'google') {
        return await callGemini(prompt, model, apiKey, baseURL);
    }
    
    // 标准 OpenAI 兼容 API（阿里云、智谱、MiniMax、Moonshot、DeepSeek、OpenAI）
    const response = await axios.post(
        `${baseURL}/chat/completions`,
        {
            model: model,
            messages: [
                { role: 'user', content: prompt }
            ],
            temperature: 0.7,
            max_tokens: 2000
        },
        {
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'Content-Type': 'application/json'
            }
        }
    );
    
    return response.data.choices[0].message.content;
}

/**
 * 调用 Anthropic Claude API
 */
async function callAnthropic(prompt, model, apiKey, baseURL) {
    const response = await axios.post(
        `${baseURL}/messages`,
        {
            model: model,
            max_tokens: 2000,
            messages: [
                { role: 'user', content: prompt }
            ]
        },
        {
            headers: {
                'x-api-key': apiKey,
                'anthropic-version': '2023-06-01',
                'Content-Type': 'application/json'
            }
        }
    );
    
    return response.data.content[0].text;
}

/**
 * 调用 Google Gemini API
 */
async function callGemini(prompt, model, apiKey, baseURL) {
    const response = await axios.post(
        `${baseURL}/models/${model}:generateContent?key=${apiKey}`,
        {
            contents: [{
                parts: [{
                    text: prompt
                }]
            }]
        },
        {
            headers: {
                'Content-Type': 'application/json'
            }
        }
    );
    
    return response.data.candidates[0].content.parts[0].text;
}

/**
 * 延时函数
 */
function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * 统一响应格式
 */
function response(statusCode, body) {
    return {
        statusCode: statusCode,
        headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*'
        },
        body: JSON.stringify(body)
    };
}

/**
 * 日志工具
 */
function log(level, ...args) {
    const timestamp = new Date().toISOString();
    console.log(`[${timestamp}][${level}]`, ...args);
}

// ==================== 本地开发服务器（便于 test.js 调用） ====================

if (require.main === module) {
    const PORT = process.env.PORT || 8000;
    
    const server = http.createServer((req, res) => {
        if (req.method !== 'POST') {
            res.writeHead(405, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ success: false, error: 'Method Not Allowed' }));
            return;
        }
        
        let body = '';
        req.on('data', chunk => {
            body += chunk.toString();
        });
        
        req.on('end', async () => {
            try {
                const result = await exports.handler({ body }, {});
                res.writeHead(result.statusCode || 500, result.headers || { 'Content-Type': 'application/json' });
                res.end(result.body || '');
            } catch (error) {
                log('ERROR', '本地服务器处理请求失败:', error.message);
                res.writeHead(500, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ success: false, error: error.message }));
            }
        });
    });
    
    const HOST = process.env.HOST || '127.0.0.1';
    server.listen(PORT, HOST, () => {
        log('INFO', `本地开发服务器已启动，http://${HOST}:${PORT}，MOCK_MODE=${isMockMode()}`);
    });
}
