// 测试脚本
// This project is generated by AI self-evolution.

const axios = require('axios');

const BASE_URL = 'http://localhost:8000';  // 本地测试，由 index.js 内置 HTTP 服务器提供
// const BASE_URL = 'https://你的函数 URL.apigateway.cn-hangzhou.aliyuncs.com';  // 线上测试

async function test(action, data = {}) {
    try {
        console.log(`\n测试：${action}`);
        const response = await axios.post(BASE_URL, {
            action,
            ...data
        }, {
            headers: { 'Content-Type': 'application/json' }
        });
        console.log('✅ 成功:', JSON.stringify(response.data, null, 2));
        return response.data;
    } catch (error) {
        if (error.response) {
            console.error('❌ 失败:', error.response.status, JSON.stringify(error.response.data, null, 2));
        } else {
            console.error('❌ 失败:', error.message);
        }
        return null;
    }
}

// 运行测试
(async () => {
    console.log('=== AutoContent Factory 测试 ===\n');
    
    // 1. 健康检查
    await test('health');
    
    // 2. 获取热点（MOCK_MODE 下会返回模拟数据）
    await test('get_hotspots', { platform: 'all', limit: 3 });
    
    // 3. 生成口播稿
    const script = await test('generate_script', {
        topic: 'AI 会不会取代程序员',
        duration: 60
    });
    
    // 4. 分析热点
    await test('analyze_hotspot', {
        topic: 'AI 会不会取代程序员',
        platform: 'youtube'
    });
    
    // 5. 发布微信公众号文章
    await test('publish_wechat', {
        title: 'AI 会不会取代程序员',
        content: '<p>这里是文章内容...</p>',
        summary: '深度解析 AI 与程序员的未来',
        tags: ['AI', '程序员', '科技']
    });
    
    // 6. 一键生成微信文章
    await test('auto_create_wechat', {
        topic: 'AI 会不会取代程序员',
        style: 'informative'
    });
    
    // 7. 生成视频（在 MOCK_MODE 或已配置视频服务时使用）
    if (script && script.data && script.data.script) {
        await test('generate_video', {
            script: script.data.script,
            video_type: 'talking_head'
        });
    }
    
    // 8. 一键生成（推荐在 MOCK_MODE 下先验证整体流程）
    await test('auto_create', {
        topic: 'AI 会不会取代程序员',
        platform: 'youtube'
    });
    
    console.log('\n=== 测试完成 ===\n');
})();
